version: '3.8'

services:
  django:
    container_name: backend
    build: .
    image: backend
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    networks:
      - log-network

networks:
  log-network:
    external: true