version: '3.8'

services:
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml -config.expand-env=true
    env_file:
      - .env
    networks:
      - log-network

networks:
  log-network:
    external: true
